import { createFlow } from "@builderbot/bot";
import { welcomeFlow } from './welcomeFlow';
import { menuFlow } from './menuFlow';
import { politicaDatosFlow } from './flujos/principal/politicasDatos';
import { noAceptaPoliticas } from './flujos/principal/noAceptaPoliticas';
import {
    menuConocerIpsFlow,
    serviciosStepConocer,
    conveniosStepConocer,
    tarifasStepConocer,
    formaspagoStepConocer,
    ubicacionStepConocer,
    horariosStepConocer,
    canalesStepConocer,
} from './flujos/conocerIps';
import {
    step1Reprogramar,
    step5Reprogramar,
    step6Reprogramar,
    step7Reprogramar,
    stepConfirmaReprogramar,
    stepSeleccionaFechaReprogramar,
    stepHoraSeleccionada,
    noConfirmaReprogramar,
    //seleccionaCitaReprogramar,
    confirmarReprogramarCita,
    revisarPagoConsulta,
    noConfirmaReprogramarCita,
    preguntarConfirmarBotones,
} from './flujos/reprogramarCita';

import {
    step1CencelarCita,
    step5CancelarCita,
    step6CancelarCita,
    step7CancelarCita,
    stepConfirmaCancelarCita,
    stepOpcionReprogramar,
} from './flujos/cancelarCita';

import {
    datosinicialesComunes,
    datosinicialesComunes2,
    datosinicialesComunes3,
    datosinicialesComunes4,
    datosinicialesComunes5,
    volverMenuPrincipal,
    mesajeSalida,
} from './flujos/common';
import { pasoAgenteFlow } from './flujos/pasoAgente';
import { ejecutarPlantillaDiariaFlow, confirmarCitaFlow } from './flujos/campahna';
import {
    step1AgendarCita,
    step2AgendarCita,
    // CONTROL
    step4AgendarCitaControl,
    step5AgendarCitaControl,
    step6AgendarCitaControlDoc,
    step6AgendarCitaControl,
    step7AgendarCitaControl,
    // PRIMERA VEZ
    step4AgendarCitaPrimeraVez,
    step5AgendarCitaPrimeraVezPresencial,
    step5AgendarCitaPrimeraVezVirtual,
    step6AgendarCitaPrimeraVezPsicologia,
    step6AgendarCitaPrimeraVezNeuropsicologia,
    step6AgendarCitaPrimeraVezPsiquiatria,
    step6AgendarCitaPrimeraVezPsicologiaAtencion,
    // PASOS GENERALES
    step8AgendarCita,
    step9AgendarCita,
    step10AgendarCita,
    step11AgendarCita,
    step12AgendarCita,
    step13AgendarCitaConvenio,
    step13AgendarCitaParticular,
    step13AgendarCitaConvenio2,
    step14AgendarCita,
    step14AgendarCita2,
    step15AgendarCita,
    step16AgendarCita,
    step17AgendarCita,
    step17AgendarCita2,
    step17AgendarCita3,
    step17AgendarCita4,
    step17AgendarCita5,
    step17AgendarCita6,
    step17AgendarCita7,
    step18AgendarCita,
    step18AgendarCita2,
    step19AgendarCita,
    step20AgendarCita,
    step21AgendarCita,
    step22AgendarCita,
    step23AgendarCita,
} from './flujos/agendarCita'

export default createFlow([
    welcomeFlow,
    politicaDatosFlow,
    noAceptaPoliticas,
    menuFlow,
    menuConocerIpsFlow,
    serviciosStepConocer,
    conveniosStepConocer,
    tarifasStepConocer,
    formaspagoStepConocer,
    ubicacionStepConocer,
    horariosStepConocer,
    canalesStepConocer,
    step1Reprogramar,
    step1CencelarCita,
    datosinicialesComunes,
    datosinicialesComunes2,
    datosinicialesComunes3,
    datosinicialesComunes4,
    datosinicialesComunes5,
    step1AgendarCita,
    step2AgendarCita,
    // CONTROL
    step4AgendarCitaControl,
    step5AgendarCitaControl,
    step6AgendarCitaControlDoc,
    step6AgendarCitaControl,
    step7AgendarCitaControl,
    // PRIMERA VEZ
    step4AgendarCitaPrimeraVez,
    step5AgendarCitaPrimeraVezPresencial,
    step5AgendarCitaPrimeraVezVirtual,
    step6AgendarCitaPrimeraVezPsicologia,
    step6AgendarCitaPrimeraVezNeuropsicologia,
    step6AgendarCitaPrimeraVezPsiquiatria,
    step6AgendarCitaPrimeraVezPsicologiaAtencion,
    // PASOS GENERALES
    step8AgendarCita,
    step9AgendarCita,
    step10AgendarCita,
    step11AgendarCita,
    step12AgendarCita,
    step13AgendarCitaConvenio,
    step13AgendarCitaParticular,
    step13AgendarCitaConvenio2,
    step14AgendarCita,
    step14AgendarCita2,
    step15AgendarCita,
    step16AgendarCita,
    step17AgendarCita,
    step17AgendarCita2,
    step17AgendarCita3,
    step17AgendarCita4,
    step17AgendarCita5,
    step17AgendarCita6,
    step17AgendarCita7,
    step18AgendarCita,
    step18AgendarCita2,
    step19AgendarCita,
    step20AgendarCita,
    step21AgendarCita,
    step22AgendarCita,
    step23AgendarCita,
    step5Reprogramar,
    step6Reprogramar,
    step7Reprogramar,
    step5CancelarCita,
    step6CancelarCita,
    step7CancelarCita,
    stepOpcionReprogramar,
    stepConfirmaReprogramar,
    stepSeleccionaFechaReprogramar,
    stepHoraSeleccionada,
    noConfirmaReprogramar,
    //seleccionaCitaReprogramar,
    confirmarReprogramarCita,
    revisarPagoConsulta,
    noConfirmaReprogramarCita,
    preguntarConfirmarBotones,
    volverMenuPrincipal,
    mesajeSalida,
    stepConfirmaCancelarCita,
    pasoAgenteFlow,
    ejecutarPlantillaDiariaFlow,
    confirmarCitaFlow,
]);